# Generated by Django 4.1.4 on 2022-12-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_follow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="follow",
            old_name="following_user_id",
            new_name="user_followed",
        ),
    ]
