# Generated by Django 4.1.4 on 2022-12-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_rename_user_id_follow_user_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("user", "user_followed")},
        ),
    ]
