# Generated by Django 4.1.4 on 2022-12-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_alter_follow_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together=set(),
        ),
    ]
